const categoryMap={"Vehicles":["Cars","Motorcycles","Bicycles","Auto Rickshaw","Trucks & Buses","Vehicle Parts"],"Property":["Land","Apartments","Houses","Shops & Commercial Space","Office Space","Property for Rent"],"Phones & Tablets":["Mobile Phones","Tablets","Phone Accessories","Smart Watches"],"Electronics":["TV","Laptop & Computer","Camera","Audio","Gaming","Other Electronics"],"Home, Furniture & Garden":["Furniture","Home Decor","Kitchen","Garden","Appliances"],"Fashion":["Men","Women","Kids","Shoes","Bags & Accessories","Watches"],"Beauty & Personal Care":["Cosmetics","Skin Care","Hair Care","Perfume","Health & Personal Care"],"Services":["Tutoring","Cleaning","Transport","Photography","IT & Digital","Other Services"],"Repair & Construction":["Electrician","Plumber","AC & Fridge Repair","Construction Materials","Mechanic","Painter"],"Commercial Equipment & Machinery":["Factory Equipment","Restaurant Equipment","Office Equipment","Tools","Machinery"],"Leisure & Activities":["Sports","Gym & Fitness","Music","Books","Tickets & Events","Hobbies"],"Babies & Kids":["Baby Products","Toys","Kids Clothing","Strollers","School Items"],"Food, Agriculture & Supplies":["Vegetables","Fruits","Fish","Livestock Feed","Seeds","Farm Products"],"Animals & Pets":["Cattle","Goat","Poultry","Pets","Pet Supplies"],"Jobs":["Full Time","Part Time","Sales Jobs","Driver Jobs","Office Jobs","Other Jobs"],"Seeking Work - CVs":["CVs","Job Seekers","Freelancers","Skilled Workers"],"Business & Industry":["Business for Sale","Wholesale","Retail","Industrial Products","Tools"]};
const money=n=>"৳ "+Number(n||0).toLocaleString("en-US");
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
async function user(){const {data}=await sb.auth.getUser();return data.user}
async function profile(){const u=await user();if(!u)return null;const {data}=await sb.from("profiles").select("*").eq("id",u.id).maybeSingle();return data}
function toast(x){const t=document.getElementById("toast");if(!t)return alert(x);t.textContent=x;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
async function fav(id){const u=await user();if(!u){location.href="login.html?next="+encodeURIComponent(location.href);return}const {data}=await sb.from("favorites").select("ad_id").eq("user_id",u.id).eq("ad_id",id).maybeSingle();if(data){await sb.from("favorites").delete().eq("user_id",u.id).eq("ad_id",id);toast("Favourite থেকে সরানো হয়েছে")}else{await sb.from("favorites").insert({user_id:u.id,ad_id:id});toast("Favourite-এ যোগ হয়েছে")}}
function card(a){const img=a.image_urls?.[0];return `<article class="product" onclick="location.href='ad-details.html?id=${encodeURIComponent(a.id)}'"><button class="heart" onclick="event.stopPropagation();fav('${a.id}')">♡</button><div class="photo" ${img?`style="background-image:url('${esc(img)}');background-size:cover;background-position:center"`:""}>${img?"":esc(a.subcategory||a.category||"AD")}</div><div class="body"><span class="badge">${esc(a.subcategory||a.category)}</span><h3>${esc(a.title)}</h3><div class="price">${money(a.price)}</div><div class="meta">⌖ ${esc(a.location||"চাঁদপুর")} · ${new Date(a.created_at).toLocaleDateString("bn-BD")}</div></div></article>`}
async function loadLatest(){const el=document.getElementById("latestAds");if(!el)return;const {data,error}=await sb.from("ads").select("*").eq("status","approved").order("created_at",{ascending:false}).limit(8);el.innerHTML=error?"<p class='muted'>বিজ্ঞাপন লোড করা যায়নি।</p>":(data?.length?data.map(card).join(""):"<p class='muted'>এখনও কোনো প্রকাশিত বিজ্ঞাপন নেই।</p>")}
async function setupHeader(){const form=document.getElementById("searchForm");if(form)form.onsubmit=e=>{e.preventDefault();const q=document.getElementById("search")?.value.trim();location.href="search.html"+(q?"?q="+encodeURIComponent(q):"")};const u=await user();const al=document.getElementById("accountLink");if(u&&al){const p=await profile();al.textContent=p?.name||"প্রোফাইল";al.href="profile.html"}}
document.addEventListener("DOMContentLoaded",async()=>{await setupHeader();await loadLatest()});
window.marketplace={categoryMap,money,esc,user,profile,toast,card,fav};
